import { Metadata } from "next";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Sign In" };

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen grid lg:grid-cols-2">
      {/* Left - Branding */}
      <div className="hidden lg:flex flex-col gradient-hero bg-[hsl(224,71%,4%)] p-12 text-white relative overflow-hidden">
        {/* Grid pattern overlay */}
        <div
          className="absolute inset-0 opacity-[0.03]"
          style={{
            backgroundImage: "linear-gradient(hsl(var(--border)) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--border)) 1px, transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        />
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-16">
            <div className="w-8 h-8 rounded-lg gradient-primary flex items-center justify-center">
              <span className="text-white text-sm font-bold">D</span>
            </div>
            <span className="font-bold text-lg">DocuMind AI</span>
          </div>
          <div className="space-y-6">
            <div>
              <h1 className="text-4xl font-bold leading-tight">
                Beautiful docs,{" "}
                <span className="gradient-text">generated by AI</span>
              </h1>
              <p className="text-white/60 mt-4 text-lg leading-relaxed">
                Upload your codebase and get comprehensive technical documentation in seconds. Supports ZIP, files, and GitHub URLs.
              </p>
            </div>
            <div className="space-y-3 mt-8">
              {[
                "31 documentation sections generated",
                "Intelligent chunking for large projects",
                "Version history & diff comparison",
                "Export as README, Markdown, or PDF",
              ].map((feature) => (
                <div key={feature} className="flex items-center gap-2 text-sm text-white/70">
                  <div className="w-1.5 h-1.5 rounded-full bg-primary shrink-0" />
                  {feature}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Right - Auth Form */}
      <div className="flex items-center justify-center p-8 bg-background">
        <div className="w-full max-w-sm">
          {children}
        </div>
      </div>
    </div>
  );
}
