import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { Metadata } from "next";
import {
  Sparkles,
  Zap,
  Shield,
  GitBranch,
  Download,
  Search,
  Star,
  ArrowRight,
  FileArchive,
  Files,
  CheckCircle2,
  Code2,
  FileText,
  Lock,
  BarChart2,
} from "lucide-react";
import { GithubIcon } from "@/components/icons/github-icon";

export const metadata: Metadata = {
  title: "DocuMind AI — AI-Powered Documentation Generator",
  description:
    "Upload your codebase and get instant, beautiful, comprehensive technical documentation. Powered by Gemini 2.5 Flash.",
};

const features = [
  {
    icon: Zap,
    title: "Instant Generation",
    description: "Upload a ZIP, files, or GitHub URL and get comprehensive documentation in under 60 seconds.",
    color: "text-yellow-500 bg-yellow-500/10",
  },
  {
    icon: Code2,
    title: "31 Doc Sections",
    description: "Overview, architecture, API docs, security, deployment guide, and 26 more sections.",
    color: "text-blue-500 bg-blue-500/10",
  },
  {
    icon: GitBranch,
    title: "Version History",
    description: "Every regeneration creates a new version. Compare, restore, or delete old versions.",
    color: "text-purple-500 bg-purple-500/10",
  },
  {
    icon: FileText,
    title: "Rich Markdown Editor",
    description: "Edit any section with live preview, auto-save, and undo/redo support.",
    color: "text-green-500 bg-green-500/10",
  },
  {
    icon: Download,
    title: "Multiple Export Formats",
    description: "Download as README.md, full Markdown, PDF, or DOCX for any use case.",
    color: "text-orange-500 bg-orange-500/10",
  },
  {
    icon: Shield,
    title: "Enterprise Security",
    description: "Row-level security, encrypted storage, rate limiting, and XSS protection built-in.",
    color: "text-red-500 bg-red-500/10",
  },
  {
    icon: Search,
    title: "Global Search",
    description: "Search across all your projects and documentation content instantly.",
    color: "text-cyan-500 bg-cyan-500/10",
  },
  {
    icon: BarChart2,
    title: "Quality Scoring",
    description: "AI evaluates your documentation on completeness, readability, and technical depth.",
    color: "text-indigo-500 bg-indigo-500/10",
  },
];

const supportedFrameworks = [
  "Next.js", "React", "Vue", "Angular", "Svelte",
  "Express", "NestJS", "FastAPI", "Django", "Flask",
  "Spring Boot", "Laravel", "Ruby on Rails", "Flutter",
  "Go", "Rust", "Python", "TypeScript",
];

export default function HomePage() {
  return (
    <div className="overflow-hidden">
      {/* Hero */}
      <section className="relative min-h-[90vh] flex items-center justify-center text-center px-4">
        {/* Background */}
        <div className="absolute inset-0 gradient-hero" />
        <div
          className="absolute inset-0 opacity-[0.02]"
          style={{
            backgroundImage:
              "linear-gradient(hsl(var(--border)) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--border)) 1px, transparent 1px)",
            backgroundSize: "60px 60px",
          }}
        />
        {/* Glow effects */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-primary/20 rounded-full blur-3xl opacity-30" />

        <div className="relative z-10 max-w-4xl mx-auto space-y-8">
          <Badge className="gradient-primary text-white border-0 px-4 py-1.5 text-sm">
            <Sparkles className="w-3.5 h-3.5 mr-1.5" />
            Powered by Gemini 2.5 Flash
          </Badge>

          <h1 className="text-5xl sm:text-6xl md:text-7xl font-black tracking-tight leading-none">
            Beautiful docs,{" "}
            <span className="gradient-text">generated by AI</span>
          </h1>

          <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Upload your codebase — ZIP, files, or a GitHub URL — and DocuMind AI analyzes every file and generates{" "}
            <strong className="text-foreground">31 sections of professional documentation</strong> in seconds.
          </p>

          {/* Upload methods */}
          <div className="flex flex-wrap items-center justify-center gap-3 text-sm">
            {[
              { icon: FileArchive, label: "ZIP Files" },
              { icon: Files, label: "Individual Files" },
              { icon: GithubIcon, label: "GitHub URL" },
            ].map(({ icon: Icon, label }) => (
              <div
                key={label}
                className="flex items-center gap-2 px-4 py-2 rounded-full border border-border bg-card/50 backdrop-blur-sm text-muted-foreground"
              >
                <Icon className="w-4 h-4" />
                {label}
              </div>
            ))}
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <Button
              size="lg"
              asChild
              className="gradient-primary text-white border-0 hover:opacity-90 h-12 px-8 text-base font-semibold shine"
              id="hero-get-started"
            >
              <Link href="/signup">
                Get Started Free <ArrowRight className="w-5 h-5 ml-2" />
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild className="h-12 px-8 text-base">
              <Link href="/login">Sign In</Link>
            </Button>
          </div>

          <p className="text-xs text-muted-foreground">
            Free plan: 5 generations/day • No credit card required
          </p>
        </div>
      </section>

      {/* What gets generated */}
      <section className="py-24 px-4 bg-muted/20">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">
              31 documentation sections, automatically
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              From executive summaries to deployment guides — AI generates everything your project needs.
            </p>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
            {[
              "Project Overview", "Executive Summary", "README.md", "Features",
              "Folder Structure", "Tech Stack", "Architecture", "Installation Guide",
              "Usage Guide", "Configuration", "Environment Variables", "Database Schema",
              "API Documentation", "Auth Flow", "Code Organization", "Major Components",
              "Reusable Modules", "Design Patterns", "Security Suggestions", "Performance Tips",
              "Code Quality", "Future Improvements", "Known Limitations", "Deployment Guide",
              "Contributing Guide", "License", "Complexity Analysis", "Dependency Analysis",
              "Project Summary", "README Badges", "Quality Score",
            ].map((section) => (
              <div
                key={section}
                className="flex items-center gap-2 p-3 rounded-lg border border-border bg-card hover:border-primary/30 transition-colors"
              >
                <CheckCircle2 className="w-3.5 h-3.5 text-green-500 shrink-0" />
                <span className="text-xs font-medium">{section}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-24 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">Everything you need</h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">
              A complete documentation platform built for modern development teams.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, i) => (
              <div
                key={feature.title}
                className="p-5 rounded-2xl border border-border bg-card hover:border-primary/30 hover:shadow-lg transition-all"
              >
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-4 ${feature.color}`}>
                  <feature.icon className="w-5 h-5" />
                </div>
                <h3 className="font-semibold mb-2 text-sm">{feature.title}</h3>
                <p className="text-xs text-muted-foreground leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Supported Frameworks */}
      <section className="py-24 px-4 bg-muted/20">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">Supports every stack</h2>
          <p className="text-muted-foreground mb-12">
            From TypeScript to Rust, React to Spring Boot — DocuMind AI understands them all.
          </p>
          <div className="flex flex-wrap justify-center gap-2">
            {supportedFrameworks.map((fw) => (
              <span
                key={fw}
                className="px-3 py-1.5 rounded-full border border-border bg-card text-sm text-muted-foreground hover:text-foreground hover:border-primary/30 transition-colors"
              >
                {fw}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-4">
        <div className="max-w-2xl mx-auto text-center">
          <div className="rounded-3xl border border-primary/20 bg-primary/5 p-12 space-y-6">
            <div className="w-16 h-16 rounded-2xl gradient-primary flex items-center justify-center mx-auto">
              <Sparkles className="w-8 h-8 text-white" />
            </div>
            <h2 className="text-3xl font-bold">Start for free today</h2>
            <p className="text-muted-foreground">
              5 free documentation generations per day. No credit card required.
            </p>
            <Button
              size="lg"
              asChild
              className="gradient-primary text-white border-0 hover:opacity-90 h-12 px-10 text-base"
              id="cta-signup"
            >
              <Link href="/signup">
                Create Free Account <ArrowRight className="w-5 h-5 ml-2" />
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
